### ISSUE TITLE
arduino-core fetch failed.

### ISSUE THREAD

**Issue by ghost** [maurerpe/arduino-overlay#1] opened 2016-04-10 17:09 UTC
> > > Downloading 'https://github.com/arduino-core/Arduino/archive/1.6.8.tar.gz'
> > > --2016-04-10 16:59:45--  https://github.com/arduino-core/Arduino/archive/1.6.8.tar.gz
> > > Resolving github.com... 192.30.252.121
> > > Connecting to github.com|192.30.252.121|:443... connected.
> > > HTTP request sent, awaiting response... 404 Not Found
> > > 2016-04-10 16:59:45 ERROR 404: Not Found.

!!! Couldn't download '1.6.8.tar.gz'. Aborting.
- Fetch failed for 'dev-embedded/arduino-core-1.6.8', Log file:
-  '/var/tmp/portage/dev-embedded/arduino-core-1.6.8/temp/build.log'

> > > Failed to emerge dev-embedded/arduino-core-1.6.8, Log file:
> > > 
> > >  '/var/tmp/portage/dev-embedded/arduino-core-1.6.8/temp/build.log'

**Comment by slavkoja** [comment] 2016-04-10 17:24
Hi,

I go to the same issue (i add it again with better formatting):

```
>>> Emerging (37 of 44) dev-embedded/arduino-core-1.6.8::arduino-overlay
>>> Downloading 'http://distfiles.gentoo.org/distfiles/1.6.8.tar.gz'
--2016-04-10 19:17:52--  http://distfiles.gentoo.org/distfiles/1.6.8.tar.gz
Resolving distfiles.gentoo.org... 216.165.129.135, 64.50.236.52, 140.211.166.134, ...
Connecting to distfiles.gentoo.org|216.165.129.135|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-04-10 19:17:52 ERROR 404: Not Found.

>>> Downloading 'https://github.com/arduino-core/Arduino/archive/1.6.8.tar.gz'
--2016-04-10 19:17:52--  https://github.com/arduino-core/Arduino/archive/1.6.8.tar.gz
Resolving github.com... 192.30.252.122
Connecting to github.com|192.30.252.122|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-04-10 19:17:52 ERROR 404: Not Found.

!!! Couldn't download '1.6.8.tar.gz'. Aborting.
 * Fetch failed for 'dev-embedded/arduino-core-1.6.8', Log file:
 *  '/var/tmp/portage/dev-embedded/arduino-core-1.6.8/temp/build.log'

>>> Failed to emerge dev-embedded/arduino-core-1.6.8, Log file:

>>>  '/var/tmp/portage/dev-embedded/arduino-core-1.6.8/temp/build.log'
```

It seems, that the proper download link is:

```
https://github.com/arduino/Arduino/archive/1.6.8.tar.gz
                   ^^^^^^^
```

**Comment by maurerpe** [comment] 2016-04-11 00:39
Oops.  Looks like I forgot to update the SRC_URI when I split the core from the ide.  arduino-ide had the same issue.  Both are fixed now.  Thanks for reporting this.

**Comment by slavkoja** [comment] 2016-04-11 16:39
Thanks, now it is fetched and emerged, but run the IDE fails with:

```
java.lang.UnsatisfiedLinkError: no listSerialsj in java.library.path
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
    at java.lang.Runtime.loadLibrary0(Runtime.java:870)
    at java.lang.System.loadLibrary(System.java:1122)
    at processing.app.Platform.<clinit>(Platform.java:148)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    at processing.app.BaseNoGui.initPlatform(BaseNoGui.java:651)
    at processing.app.Base.guardedMain(Base.java:148)
    at processing.app.Base.main(Base.java:132)
```

**Comment by maurerpe** [comment] 2016-04-12 02:45
You need dev-libs/libserialport, which is in the overlay.  Looks like the issue is that I forgot a dependancy on arduino-ide.  I added dev-embedded/listerialportsc, which should pull in dev-libs/libserialport.

Resync and emerge arduino-ide again.  It should pull in the new dependencies automatically.

**Comment by slavkoja** [comment] 2016-04-13 16:49
I am sorry, i didn't test it again, because there is problem to get `gcc-avr` to compile on funtoo now, then your ebuilds are useless for me yet.

**Closed as completed** 2016-04-16 22:34 UTC
